# Read the Docs 配置文件
# 详情请参见 https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

sphinx:
   configuration: docs/source/conf.py

# 如果使用 Sphinx，可以选择将文档构建为其他格式，例如 PDF
formats:
   - pdf

# 可选择性地声明构建文档所需的 Python 依赖
python:
   install:
   - requirements: docs/requirements-docs.txt
